<template>
    <div class="jsx">
        <h2>ExtendScript</h2>
        <!-- <div class="row">
            <div class="topcoat-button-bar">
                <div class="topcoat-button-bar__item">
                    <button class="topcoat-button-bar__button--large" v-on:click="toggleScriptListener" v-bind:style="{ color: isScriptListening ? '#0f0' : '#f00'}">Toggle ScriptListener</button>
                </div>
                <div class="topcoat-button-bar__item">
                    <button class="topcoat-button-bar__button--large" v-on:click="clearScriptListener">Clear ScriptListener</button>
                </div>
            </div>
        </div> -->
        <div class="row">
            <label style="display: inline-block; margin-right: .5em;">
                <input class="topcoat-text-input--large" type="text" ref="charId" placeholder="CharID" v-model="charId" v-on:change="calculateStringId" v-on:focus="$event.target.select()"/> 
            </label>
            <label style="display: inline-block;">
                <input class="topcoat-text-input--large" type="text" ref="stringId" placeholder="StringID" v-model="stringId" v-on:change="calculateCharId" v-on:focus="$event.target.select()"/>
            </label>
        </div>
        <div class="row">
            <textarea class="topcoat-textarea" v-model="jsxText" rows="14" cols="45"></textarea>
            <br/><br/>
            <!-- <button class="topcoat-button--large" v-show="jsxText.length > 0" >Save as Action</button> -->
            <button class="topcoat-button--large" v-show="jsxText.length > 0" v-on:click="runJsxText">Run</button>
            <button class="topcoat-button--large" v-show="jsxText.length > 0" v-on:click="clearJsxText">Clear</button>
        </div>
    </div>
</template>

<script>
/* npm modules */
import upath from 'upath';
import fs from 'fs';
import chokidar from 'chokidar';
import debounce from 'debounce'; 

/* local modules */
import global from '../global';

const SCRIPT_LOG_PATH = "C:/Users/puglisij/Desktop/ScriptingListenerJS.log";

export default {
    name: "jsx",
    computed: {
        cs() { return global.cs; }
    },
    data: () => ({
        charId: "",
        stringId: "",
        jsxText: "",
        isScriptListening: false,
        scriptWatcher: null 
    }),
    methods: {
        clearJsxText() {
            this.jsxText = "";
        },
        runJsxText() {
            this.cs.evalScript(`` + this.jsxText, function(result) {
                console.log(`JSX Result: ${result}`)
            });
        },
        clearScriptListener() 
        {
            fs.writeFile(SCRIPT_LOG_PATH, "", err => 
            {
                if(err) throw err; 

                this.$root.$notify({
                    group: "mario", 
                    title: "Success!",
                    text: `ScriptListenerLog was cleared.`
                })
            })
        },
        toggleScriptListener() 
        {
            if(this.isScriptListening) {
                // Switch logging off 
                this.isScriptListening = false;
            } else {
                // Switch logging on
                this.isScriptListening = true;
            }
            this.cs.evalScript(`
            var listenerID = stringIDToTypeID("AdobeScriptListener ScriptListener");
            var keyLogID = charIDToTypeID('Log ');
            var d = new ActionDescriptor;
            d.putBoolean(keyLogID, ${this.isScriptListening});
            executeAction(listenerID, d, DialogModes.NO);
            `);

            this.scriptWatcher && this.scriptWatcher.close();
            this.scriptWatcher = null;

            if(this.isScriptListening) 
            {
                this.scriptWatcher = chokidar.watch(SCRIPT_LOG_PATH);
                this.scriptWatcher.on("change", debounce(this.readScriptListenerLog, 1000));
            }

            this.$root.$notify({
                group: "mario",
                title: "Success!",
                text: `ScriptListener is: ${this.isScriptListening ? "On" : "Off"}`
            })
        },
        readScriptListenerLog(path) 
        {
            console.log("script log changed: " + path);

            // IMPORTANT: Somme commands generated by ScriptListenerPlugin will not run via evalScript.
            //  In particular, modal commands, such as "modalStateChanged" will throw an error
            fs.readFile(path, (err, data) => {
                if(err) throw err; 

                this.jsxText = data.toString();
            })
        },
        calculateStringId() {
            this.cs.evalScript(`typeIDToStringID(charIDToTypeID('${this.charId}'))`, result => {
                if(result.includes("error")) {
                    return;
                }
                this.stringId = "// " + result;
                this.$nextTick(() => {
                    this.$refs.stringId.focus();
                    this.$refs.stringId.select();
                })
            })
        },
        calculateCharId() {
            this.cs.evalScript(`typeIDToCharID(stringIDToTypeID('${this.stringId}'))`, result => {
                if(result.includes("error")) {
                    return;
                }
                this.charId = result;
                this.$nextTick(() => {
                    this.$refs.charId.focus();
                    this.$refs.charId.select();
                })
            })
        }
    }
};
</script>

<style scoped>
    .row {
        margin-bottom: .5em;
    }
</style>