<template>
    <div class="jsx">
        <h2>ExtendScript</h2>

        <button v-on:click="toggleScriptListener" v-bind:style="{ color: isScriptListening ? '#0f0' : '#f00'}">Toggle ScriptListener</button>
        <button v-on:click="clearScriptListener">Clear ScriptListener</button>

        <div style="margin: 10px 0;">
            <label style="display: inline-block">
                CharID <br>
                <input type="text" ref="charId" v-model="charId" v-on:change="calculateStringId" v-on:focus="$event.target.select()"/> 
            </label>
            <span style="margin: 0 10px"></span>
            <label style="display: inline-block">
                StringID <br>
                <input type="text" ref="stringId" v-model="stringId" v-on:change="calculateCharId" v-on:focus="$event.target.select()"/>
            </label>
        </div>
        <div style="margin: 10px 0;">
            <textarea v-model="jsxText" rows="16" cols="60"></textarea>
            <br/>
            <button v-show="jsxText.length > 0" v-on:click="runJsxText">Run</button>
        </div>
    </div>
</template>

<script>
/* npm modules */
import upath from 'upath';
import { mapState, mapGetters } from 'vuex';
import fs from 'fs';
import chokidar from 'chokidar';
import debounce from 'debounce'; 

const SCRIPT_LOG_PATH = "C:/Users/puglisij/Desktop/ScriptingListenerJS.log";

export default {
    name: "jsx",
    computed: {
        ...mapState(['cs'])
    },
    data: () => ({
        charId: "",
        stringId: "",
        jsxText: "",
        isScriptListening: false,
        scriptWatcher: null 
    }),
    methods: {
        runJsxText() {
            this.cs.evalScript(``+this.jsxText, function(result) {
                console.log(`JSX Result: ${result}`)
            });
        },
        clearScriptListener() 
        {
            fs.writeFile(SCRIPT_LOG_PATH, "", err => 
            {
                if(err) throw err; 

                this.$root.$notify({
                    group: "mario", 
                    title: "Success!",
                    text: `ScriptListenerLog was cleared.`
                })
            })
        },
        toggleScriptListener() 
        {
            if(this.isScriptListening) {
                // Switch logging off 
                this.isScriptListening = false;
            } else {
                // Switch logging on
                this.isScriptListening = true;
            }
            this.cs.evalScript(`
            var listenerID = stringIDToTypeID("AdobeScriptListener ScriptListener");
            var keyLogID = charIDToTypeID('Log ');
            var d = new ActionDescriptor;
            d.putBoolean(keyLogID, ${this.isScriptListening});
            executeAction(listenerID, d, DialogModes.NO);
            `);

            this.scriptWatcher && this.scriptWatcher.close();
            this.scriptWatcher = null;

            if(this.isScriptListening) 
            {
                this.scriptWatcher = chokidar.watch(SCRIPT_LOG_PATH);
                this.scriptWatcher.on("change", debounce(this.readScriptListenerLog, 2000));
            }

            this.$root.$notify({
                group: "mario",
                title: "Success!",
                text: `ScriptListener is: ${this.isScriptListening ? "On" : "Off"}`
            })
        },
        readScriptListenerLog(path) 
        {
            console.log("script log changed: " + path);

            // IMPORTANT: Somme commands generated by ScriptListenerPlugin will not run via evalScript.
            //  In particular, modal commands, such as "modalStateChanged" will throw an error
            fs.readFile(path, (err, data) => {
                if(err) throw err; 

                this.jsxText = data.toString();
            })
        },
        calculateStringId() {
            this.cs.evalScript(`typeIDToStringID(charIDToTypeID('${this.charId}'))`, result => {
                if(result.includes("error")) {
                    return;
                }
                this.stringId = "// " + result;
                this.$nextTick(() => {
                    this.$refs.stringId.focus();
                    this.$refs.stringId.select();
                })
            })
        },
        calculateCharId() {
            this.cs.evalScript(`typeIDToCharID(stringIDToTypeID('${this.stringId}'))`, result => {
                if(result.includes("error")) {
                    return;
                }
                this.charId = result;
                this.$nextTick(() => {
                    this.$refs.charId.focus();
                    this.$refs.charId.select();
                })
            })
        }
    }
};
</script>

<style>
    .jsx {
        margin: 10px 0;
    }
</style>