<template>
    <div class="jsx">
        <h2>ExtendScript</h2>
        <div class="controls scriptlistener">
            <div class="button">
                <button class="topcoat-button--large" 
                    @click="toggleScriptListener" 
                >
                    Toggle ScriptListener {{ isScriptListening ? 'Off' : 'On'}}
                </button>
            </div>
            <div class="button">
                <button class="topcoat-button--large" 
                    @click="clearScriptListener"
                >
                    Clear ScriptListener
                </button>
            </div>
        </div>
        <div class="controls identifiers">
            <label>
                <input class="topcoat-text-input--large" type="text" ref="charId" placeholder="CharID" v-model="charId" v-on:change="calculateStringId" v-on:focus="$event.target.select()"/> 
            </label>
            <label>
                <input class="topcoat-text-input--large" type="text" ref="stringId" placeholder="StringID" v-model="stringId" v-on:change="calculateCharId" v-on:focus="$event.target.select()"/>
            </label>
        </div>
        <div class="controls code">
            <textarea class="topcoat-textarea" v-model="jsxText" rows="14" cols="45"></textarea>
            <br/><br/>
            <!-- <button class="topcoat-button--large" v-show="jsxText.length > 0" >Save as Action</button> -->
            <button class="topcoat-button--large" v-show="jsxText.length > 0" @click="runJsxText">Run</button>
            <button class="topcoat-button--large" v-show="jsxText.length > 0" @click="clearJsx">Clear</button>
            <button class="topcoat-button--large" v-show="jsxResult.length > 0" @click="clearJsxResult">Clear Result</button>
        </div>
        <div class="result">
            <span>Result: </span> 
            <pre>{{ jsxResult }}</pre>
        </div>
    </div>
</template>

<script>
/* npm modules */
import upath from 'upath';
import fs from 'fs';
import chokidar from 'chokidar';
import debounce from 'debounce'; 

/* local modules */
import global from '../global';

// TODO: Remove hardcoded path
const SCRIPT_LOG_PATH = "C:/Users/puglisij/Desktop/ScriptingListenerJS.log";

export default {
    name: "jsx",
    computed: {
        cs() { return global.cs; }
    },
    data() {
        return {
            charId: "",
            stringId: "",
            jsxText: "",
            jsxResult: "",
            isScriptListening: false,
            scriptWatcher: null 
        }
    },
    beforeDestroy() {
        this.destroyScriptListener();
    },
    methods: {
        startScriptListener()
        {
            this.scriptWatcher = chokidar.watch(SCRIPT_LOG_PATH);
            this.scriptWatcher.on("change", debounce(this.readScriptListenerLog, 1000));
        },
        destroyScriptListener()
        {
            if(this.scriptWatcher) {
                this.scriptWatcher.removeAllListeners();
                this.scriptWatcher.close();
                this.scriptWatcher = null;
            }
        },
        clearJsxResult() {
            this.jsxResult = "";
        },
        clearJsx() {
            this.jsxText = "";
            this.jsxResult = "";
        },
        runJsxText() {
            this.cs.evalScript(`` + this.jsxText, result => {
                this.jsxResult = result.trim();
                console.log(`JSX Result: ${result}`);
            });
        },
        clearScriptListener() 
        {
            fs.writeFile(SCRIPT_LOG_PATH, "", err => 
            {
                if(err) throw err; 
            })
        },
        toggleScriptListener() 
        {
            if(this.isScriptListening) {
                // Switch logging off 
                this.isScriptListening = false;
            } else {
                // Switch logging on
                this.isScriptListening = true;
            }
            this.cs.evalScript(`
            var listenerID = stringIDToTypeID("AdobeScriptListener ScriptListener");
            var keyLogID = charIDToTypeID('Log ');
            var d = new ActionDescriptor;
            d.putBoolean(keyLogID, ${this.isScriptListening});
            executeAction(listenerID, d, DialogModes.NO);
            `);

            this.destroyScriptListener();
            if(this.isScriptListening) 
                this.startScriptListener();
        },
        readScriptListenerLog(path) 
        {
            console.log("script log changed: " + path);

            // IMPORTANT: Somme commands generated by ScriptListenerPlugin will not run via evalScript.
            //  In particular, modal commands, such as "modalStateChanged" will throw an error
            fs.readFile(path, (err, data) => {
                if(err) throw err; 

                this.jsxText = data.toString();
            })
        },
        calculateStringId() {
            this.cs.evalScript(`typeIDToStringID(charIDToTypeID('${this.charId}'))`, result => {
                if(result.includes("error")) {
                    return;
                }
                this.stringId = "// " + result;
                this.$nextTick(() => {
                    this.$refs.stringId.focus();
                    this.$refs.stringId.select();
                })
            })
        },
        calculateCharId() {
            this.cs.evalScript(`typeIDToCharID(stringIDToTypeID('${this.stringId}'))`, result => {
                if(result.includes("error")) {
                    return;
                }
                this.charId = result;
                this.$nextTick(() => {
                    this.$refs.charId.focus();
                    this.$refs.charId.select();
                })
            })
        }
    }
};
</script>

<style lang="scss">
    .jsx {
        .scriptlistener {
            display: flex;
            .button {
                margin-right: .5em;
                width: 47.5%;
            }
            button {
                width: 100%;
            }
        }
        .identifiers {
            display: flex;
            label {
                margin-right: .5em;
                width: 47.5%;
            }
            input {
                width: 100%;
            }
        }
        .code {
            textarea {
                width: calc(95% + .5em);
            }
            button {
                margin-right: .5em;
            }
        }
        .result {
            background: rgba(0,0,0,0.2);
            margin-top: 1em;
            padding: 1em;
            width: calc(95% + .5em);
        }
    }
</style>